[2023-09-05T13:44:41.508+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ganza_dag_v9.greet manual__2023-09-05T13:44:37.932980+00:00 [queued]>
[2023-09-05T13:44:41.519+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ganza_dag_v9.greet manual__2023-09-05T13:44:37.932980+00:00 [queued]>
[2023-09-05T13:44:41.520+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-05T13:44:41.535+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): greet> on 2023-09-05 13:44:37.932980+00:00
[2023-09-05T13:44:41.542+0000] {standard_task_runner.py:57} INFO - Started process 7867 to run task
[2023-09-05T13:44:41.545+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ganza_dag_v9', 'greet', 'manual__2023-09-05T13:44:37.932980+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/my_second_dag.py', '--cfg-path', '/tmp/tmpdl8x8gxv']
[2023-09-05T13:44:41.548+0000] {standard_task_runner.py:85} INFO - Job 93: Subtask greet
[2023-09-05T13:44:41.599+0000] {task_command.py:415} INFO - Running <TaskInstance: ganza_dag_v9.greet manual__2023-09-05T13:44:37.932980+00:00 [running]> on host 2729c554a115
[2023-09-05T13:44:41.684+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ganza_m' AIRFLOW_CTX_DAG_ID='ganza_dag_v9' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2023-09-05T13:44:37.932980+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-05T13:44:37.932980+00:00'
[2023-09-05T13:44:41.685+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 1 required positional argument: 'name'
[2023-09-05T13:44:41.694+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ganza_dag_v9, task_id=greet, execution_date=20230905T134437, start_date=20230905T134441, end_date=20230905T134441
[2023-09-05T13:44:41.707+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 93 for task greet (greet() missing 1 required positional argument: 'name'; 7867)
[2023-09-05T13:44:41.717+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-05T13:44:41.740+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
