[2023-09-05T14:26:47.474+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ganza_dag_v12.greet manual__2023-09-05T14:26:44.275887+00:00 [queued]>
[2023-09-05T14:26:47.487+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ganza_dag_v12.greet manual__2023-09-05T14:26:44.275887+00:00 [queued]>
[2023-09-05T14:26:47.487+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-05T14:26:47.504+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): greet> on 2023-09-05 14:26:44.275887+00:00
[2023-09-05T14:26:47.511+0000] {standard_task_runner.py:57} INFO - Started process 9620 to run task
[2023-09-05T14:26:47.515+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ganza_dag_v12', 'greet', 'manual__2023-09-05T14:26:44.275887+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/my_second_dag.py', '--cfg-path', '/tmp/tmpu51ijcnk']
[2023-09-05T14:26:47.518+0000] {standard_task_runner.py:85} INFO - Job 110: Subtask greet
[2023-09-05T14:26:47.577+0000] {task_command.py:415} INFO - Running <TaskInstance: ganza_dag_v12.greet manual__2023-09-05T14:26:44.275887+00:00 [running]> on host 2729c554a115
[2023-09-05T14:26:47.688+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ganza_m' AIRFLOW_CTX_DAG_ID='ganza_dag_v12' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2023-09-05T14:26:44.275887+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-05T14:26:44.275887+00:00'
[2023-09-05T14:26:47.690+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 1 required positional argument: 'age'
[2023-09-05T14:26:47.700+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ganza_dag_v12, task_id=greet, execution_date=20230905T142644, start_date=20230905T142647, end_date=20230905T142647
[2023-09-05T14:26:47.717+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 110 for task greet (greet() missing 1 required positional argument: 'age'; 9620)
[2023-09-05T14:26:47.766+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-05T14:26:47.810+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
