[2023-09-06T08:22:00.419+0000] {processor.py:157} INFO - Started process (PID=2585) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:22:00.421+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:22:00.422+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:22:00.422+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:22:00.436+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:22:00.432+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:22:00.436+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:22:00.485+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.072 seconds
[2023-09-06T08:22:07.507+0000] {processor.py:157} INFO - Started process (PID=2590) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:22:07.509+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:22:07.513+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:22:07.510+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:22:07.522+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:22:07.521+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:22:07.523+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:22:07.590+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.094 seconds
[2023-09-06T08:22:10.672+0000] {processor.py:157} INFO - Started process (PID=2607) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:22:10.673+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:22:10.674+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:22:10.674+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:22:10.679+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:22:10.678+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:22:10.680+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:22:10.711+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.045 seconds
[2023-09-06T08:22:41.110+0000] {processor.py:157} INFO - Started process (PID=2629) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:22:41.113+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:22:41.115+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:22:41.115+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:22:41.122+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:22:41.120+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:22:41.123+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:22:41.150+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.049 seconds
[2023-09-06T08:23:11.592+0000] {processor.py:157} INFO - Started process (PID=2651) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:23:11.595+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:23:11.598+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:23:11.597+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:23:11.610+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:23:11.605+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:23:11.611+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:23:11.665+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.089 seconds
[2023-09-06T08:23:42.106+0000] {processor.py:157} INFO - Started process (PID=2673) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:23:42.109+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:23:42.110+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:23:42.110+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:23:42.115+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:23:42.113+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:23:42.116+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:23:42.139+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.040 seconds
[2023-09-06T08:24:12.522+0000] {processor.py:157} INFO - Started process (PID=2694) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:12.523+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:24:12.524+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:24:12.524+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:12.528+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:24:12.527+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:24:12.529+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:12.592+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.079 seconds
[2023-09-06T08:24:38.830+0000] {processor.py:157} INFO - Started process (PID=2704) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:38.832+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:24:38.833+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:24:38.833+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:38.839+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:24:38.838+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:24:38.840+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:38.872+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.047 seconds
[2023-09-06T08:24:43.984+0000] {processor.py:157} INFO - Started process (PID=2721) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:43.987+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:24:43.990+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:24:43.989+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:43.999+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:24:43.997+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:24:44.000+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:44.026+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.055 seconds
[2023-09-06T08:24:46.041+0000] {processor.py:157} INFO - Started process (PID=2726) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:46.043+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:24:46.044+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:24:46.043+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:46.059+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:24:46.047+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:24:46.060+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:46.097+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.062 seconds
[2023-09-06T08:24:49.098+0000] {processor.py:157} INFO - Started process (PID=2731) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:49.101+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:24:49.104+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:24:49.102+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:49.109+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:24:49.108+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:24:49.110+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:49.145+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.051 seconds
[2023-09-06T08:24:51.183+0000] {processor.py:157} INFO - Started process (PID=2736) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:51.187+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:24:51.190+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:24:51.189+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:51.197+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:24:51.195+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:24:51.198+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:51.221+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.048 seconds
[2023-09-06T08:24:54.270+0000] {processor.py:157} INFO - Started process (PID=2741) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:54.271+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:24:54.273+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:24:54.273+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:54.278+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:24:54.277+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:24:54.279+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:24:54.305+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.050 seconds
[2023-09-06T08:25:09.486+0000] {processor.py:157} INFO - Started process (PID=2751) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:09.493+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:25:09.497+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:09.495+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:09.515+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:09.512+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:25:09.517+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:09.555+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.088 seconds
[2023-09-06T08:25:11.629+0000] {processor.py:157} INFO - Started process (PID=2768) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:11.632+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:25:11.635+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:11.634+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:11.649+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:11.644+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:25:11.651+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:11.709+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.095 seconds
[2023-09-06T08:25:15.703+0000] {processor.py:157} INFO - Started process (PID=2773) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:15.704+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:25:15.706+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:15.706+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:15.713+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:15.711+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:25:15.713+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:15.759+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.063 seconds
[2023-09-06T08:25:18.777+0000] {processor.py:157} INFO - Started process (PID=2778) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:18.779+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:25:18.781+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:18.780+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:18.786+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:18.784+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 31
    first name = get_name()
          ^
SyntaxError: invalid syntax
[2023-09-06T08:25:18.787+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:18.819+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.048 seconds
[2023-09-06T08:25:20.898+0000] {processor.py:157} INFO - Started process (PID=2783) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:20.900+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:25:20.902+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:20.901+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:20.910+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:20.908+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:25:20.911+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:20.939+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.061 seconds
[2023-09-06T08:25:26.962+0000] {processor.py:157} INFO - Started process (PID=2788) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:26.963+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:25:26.964+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:26.964+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:26.968+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:26.967+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:25:26.968+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:26.989+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.032 seconds
[2023-09-06T08:25:28.241+0000] {processor.py:157} INFO - Started process (PID=2798) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:28.242+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:25:28.243+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:28.243+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:28.248+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:28.247+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:25:28.249+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:28.275+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.038 seconds
[2023-09-06T08:25:43.456+0000] {processor.py:157} INFO - Started process (PID=2815) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:43.457+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:25:43.459+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:43.458+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:43.464+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:43.462+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:25:43.464+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:43.484+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.033 seconds
[2023-09-06T08:25:45.503+0000] {processor.py:157} INFO - Started process (PID=2820) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:45.504+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:25:45.506+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:45.505+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:45.513+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:45.512+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:25:45.513+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:45.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.043 seconds
[2023-09-06T08:25:49.558+0000] {processor.py:157} INFO - Started process (PID=2825) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:49.559+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:25:49.560+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:49.560+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:49.565+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:49.564+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:25:49.565+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:49.584+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.031 seconds
[2023-09-06T08:25:54.607+0000] {processor.py:157} INFO - Started process (PID=2830) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:54.609+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:25:54.610+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:54.609+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:54.616+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:54.614+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:25:54.616+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:54.642+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.039 seconds
[2023-09-06T08:25:55.643+0000] {processor.py:157} INFO - Started process (PID=2835) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:55.644+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:25:55.646+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:55.646+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:55.652+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:55.650+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:25:55.652+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:55.678+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.040 seconds
[2023-09-06T08:25:56.721+0000] {processor.py:157} INFO - Started process (PID=2840) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:56.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:25:56.723+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:56.723+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:56.729+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:25:56.727+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:25:56.730+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:25:56.758+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.046 seconds
[2023-09-06T08:26:27.154+0000] {processor.py:157} INFO - Started process (PID=2862) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:26:27.157+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:26:27.160+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:26:27.159+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:26:27.169+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:26:27.166+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:26:27.170+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:26:27.200+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.064 seconds
[2023-09-06T08:26:57.632+0000] {processor.py:157} INFO - Started process (PID=2884) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:26:57.634+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:26:57.636+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:26:57.635+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:26:57.641+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:26:57.639+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:26:57.641+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:26:57.664+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.040 seconds
[2023-09-06T08:27:28.044+0000] {processor.py:157} INFO - Started process (PID=2906) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:27:28.044+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:27:28.046+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:27:28.045+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:27:28.052+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:27:28.049+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:27:28.052+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:27:28.079+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.039 seconds
[2023-09-06T08:27:58.415+0000] {processor.py:157} INFO - Started process (PID=2928) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:27:58.417+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:27:58.418+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:27:58.417+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:27:58.421+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:27:58.420+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:27:58.421+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:27:58.446+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.036 seconds
[2023-09-06T08:28:28.893+0000] {processor.py:157} INFO - Started process (PID=2950) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:28:28.895+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:28:28.897+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:28:28.896+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:28:28.904+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:28:28.902+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 7, in <module>
    'retry_delay': timedelta(minutes=5)
NameError: name 'timedelta' is not defined
[2023-09-06T08:28:28.904+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:28:28.963+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.078 seconds
[2023-09-06T08:28:54.447+0000] {processor.py:157} INFO - Started process (PID=2972) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:28:54.449+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:28:54.450+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:28:54.450+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:28:54.454+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:28:54.452+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 12, in <module>
    start_date=datetime(2023, 9, 5),
NameError: name 'datetime' is not defined
[2023-09-06T08:28:54.454+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:28:54.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2023-09-06T08:29:24.739+0000] {processor.py:157} INFO - Started process (PID=2994) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:29:24.742+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:29:24.750+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:29:24.744+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:29:24.760+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:29:24.756+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 12, in <module>
    start_date=datetime(2023, 9, 5),
NameError: name 'datetime' is not defined
[2023-09-06T08:29:24.762+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:29:24.809+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.079 seconds
[2023-09-06T08:29:41.004+0000] {processor.py:157} INFO - Started process (PID=3004) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:29:41.009+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:29:41.013+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:29:41.011+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:29:41.025+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:29:41.023+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 14, in <module>
    start_date=datetime(2023, 9, 5),
NameError: name 'datetime' is not defined
[2023-09-06T08:29:41.027+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:29:41.063+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.078 seconds
[2023-09-06T08:29:44.110+0000] {processor.py:157} INFO - Started process (PID=3016) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:29:44.111+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:29:44.112+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:29:44.112+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:29:44.135+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:29:44.128+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 38, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 36, in hello_world_etl
    greet(name['first_name'], name['last_name'], age['age'])
NameError: name 'name' is not defined
[2023-09-06T08:29:44.136+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:29:44.164+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.060 seconds
[2023-09-06T08:30:12.474+0000] {processor.py:157} INFO - Started process (PID=3031) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:12.476+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:30:12.477+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:12.476+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:12.494+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:12.491+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 38, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 36, in hello_world_etl
    greet(name['first_name'], name['last_name'], age['age'])
NameError: name 'name' is not defined
[2023-09-06T08:30:12.495+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:12.527+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.058 seconds
[2023-09-06T08:30:15.548+0000] {processor.py:157} INFO - Started process (PID=3043) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:15.551+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:30:15.553+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:15.552+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:15.577+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:15.574+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 38, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 36, in hello_world_etl
    greet(name['first_name'], name['last_name'], age['age'])
NameError: name 'name' is not defined
[2023-09-06T08:30:15.580+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:15.623+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.106 seconds
[2023-09-06T08:30:21.686+0000] {processor.py:157} INFO - Started process (PID=3053) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:21.688+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:30:21.689+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:21.688+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:21.700+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:21.698+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 35, in hello_world_etl
    ns
NameError: name 'ns' is not defined
[2023-09-06T08:30:21.701+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:21.732+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.051 seconds
[2023-09-06T08:30:22.792+0000] {processor.py:157} INFO - Started process (PID=3058) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:22.793+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:30:22.794+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:22.794+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:22.813+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:22.810+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 35, in hello_world_etl
    na
NameError: name 'na' is not defined
[2023-09-06T08:30:22.814+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:22.850+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.063 seconds
[2023-09-06T08:30:25.826+0000] {processor.py:157} INFO - Started process (PID=3063) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:25.828+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:30:25.830+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:25.830+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:25.847+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:25.844+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 35, in hello_world_etl
    name
NameError: name 'name' is not defined
[2023-09-06T08:30:25.848+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:25.877+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.058 seconds
[2023-09-06T08:30:26.859+0000] {processor.py:157} INFO - Started process (PID=3068) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:26.860+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:30:26.862+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:26.861+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:26.880+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:27.025+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:27.025+0000] {manager.py:501} INFO - Created Permission View: can delete on DAG:ganza_dag_v14
[2023-09-06T08:30:27.042+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:27.042+0000] {manager.py:501} INFO - Created Permission View: can edit on DAG:ganza_dag_v14
[2023-09-06T08:30:27.051+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:27.051+0000] {manager.py:501} INFO - Created Permission View: can read on DAG:ganza_dag_v14
[2023-09-06T08:30:27.069+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:27.069+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:30:27.082+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:27.082+0000] {dag.py:2929} INFO - Creating ORM DAG for ganza_dag_v14
[2023-09-06T08:30:27.096+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:27.096+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-06T08:30:27.117+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.266 seconds
[2023-09-06T08:30:57.479+0000] {processor.py:157} INFO - Started process (PID=3102) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:57.484+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:30:57.489+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:57.487+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:57.527+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:30:57.579+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:57.578+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:30:57.625+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:30:57.624+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:30:57.652+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.190 seconds
[2023-09-06T08:31:28.110+0000] {processor.py:157} INFO - Started process (PID=3124) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:31:28.112+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:31:28.114+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:31:28.113+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:31:28.145+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:31:28.214+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:31:28.213+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:31:28.276+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:31:28.275+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:31:28.326+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.226 seconds
[2023-09-06T08:31:38.453+0000] {processor.py:157} INFO - Started process (PID=3134) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:31:38.456+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:31:38.459+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:31:38.458+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:31:38.492+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:31:38.581+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:31:38.581+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:31:38.643+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:31:38.642+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:31:38.692+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.248 seconds
[2023-09-06T08:31:42.626+0000] {processor.py:157} INFO - Started process (PID=3139) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:31:42.627+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:31:42.629+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:31:42.628+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:31:42.667+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:31:42.734+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:31:42.734+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:31:42.808+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:31:42.807+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:31:42.873+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.256 seconds
[2023-09-06T08:32:13.423+0000] {processor.py:157} INFO - Started process (PID=3167) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:32:13.425+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:32:13.427+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:32:13.427+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:32:13.460+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:32:13.586+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:32:13.582+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:32:13.744+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:32:13.742+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:32:13.811+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.402 seconds
[2023-09-06T08:32:43.985+0000] {processor.py:157} INFO - Started process (PID=3189) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:32:43.989+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:32:43.995+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:32:43.994+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:32:44.023+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:32:44.080+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:32:44.079+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:32:44.121+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:32:44.121+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:32:44.141+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.180 seconds
[2023-09-06T08:33:14.290+0000] {processor.py:157} INFO - Started process (PID=3219) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:33:14.292+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:33:14.293+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:33:14.292+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:33:14.312+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:33:14.349+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:33:14.349+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:33:14.382+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:33:14.381+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:33:14.409+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.123 seconds
[2023-09-06T08:33:44.811+0000] {processor.py:157} INFO - Started process (PID=3247) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:33:44.820+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:33:44.831+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:33:44.830+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:33:44.890+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:33:44.953+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:33:44.953+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:33:45.004+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:33:45.003+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:33:45.061+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.263 seconds
[2023-09-06T08:34:15.424+0000] {processor.py:157} INFO - Started process (PID=3269) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:34:15.429+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:34:15.432+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:34:15.431+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:34:15.489+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:34:15.534+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:34:15.534+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:34:15.567+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:34:15.567+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:34:15.586+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.177 seconds
[2023-09-06T08:34:25.688+0000] {processor.py:157} INFO - Started process (PID=3279) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:34:25.690+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:34:25.691+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:34:25.691+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:34:25.706+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:34:25.702+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name['name'], age['age'])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'age'
[2023-09-06T08:34:25.707+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:34:25.736+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.052 seconds
[2023-09-06T08:34:56.043+0000] {processor.py:157} INFO - Started process (PID=3301) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:34:56.046+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:34:56.049+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:34:56.048+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:34:56.080+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:34:56.075+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name['name'], age['age'])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'age'
[2023-09-06T08:34:56.081+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:34:56.103+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.071 seconds
[2023-09-06T08:35:12.289+0000] {processor.py:157} INFO - Started process (PID=3311) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:35:12.291+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:35:12.292+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:35:12.292+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:35:12.308+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:35:12.304+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name['name'], age['age'])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'age'
[2023-09-06T08:35:12.308+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:35:12.327+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.045 seconds
[2023-09-06T08:35:14.356+0000] {processor.py:157} INFO - Started process (PID=3316) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:35:14.357+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:35:14.359+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:35:14.358+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:35:14.392+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:35:14.385+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name['name'], age['age'])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'age'
[2023-09-06T08:35:14.392+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:35:14.429+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.082 seconds
[2023-09-06T08:35:18.507+0000] {processor.py:157} INFO - Started process (PID=3329) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:35:18.509+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:35:18.511+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:35:18.510+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:35:18.530+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:35:18.525+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name['name'], age['age'])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'age'
[2023-09-06T08:35:18.531+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:35:18.553+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.054 seconds
[2023-09-06T08:35:48.878+0000] {processor.py:157} INFO - Started process (PID=3351) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:35:48.882+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:35:48.885+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:35:48.884+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:35:48.918+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:35:48.913+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name['name'], age['age'])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'age'
[2023-09-06T08:35:48.919+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:35:48.944+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.081 seconds
[2023-09-06T08:36:19.463+0000] {processor.py:157} INFO - Started process (PID=3373) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:36:19.466+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:36:19.469+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:36:19.467+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:36:19.555+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:36:19.536+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name['name'], age['age'])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'age'
[2023-09-06T08:36:19.556+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:36:19.602+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.148 seconds
[2023-09-06T08:36:49.847+0000] {processor.py:157} INFO - Started process (PID=3395) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:36:49.849+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:36:49.850+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:36:49.850+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:36:49.864+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:36:49.860+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name['name'], age['age'])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'age'
[2023-09-06T08:36:49.865+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:36:49.884+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.042 seconds
[2023-09-06T08:37:20.262+0000] {processor.py:157} INFO - Started process (PID=3417) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:37:20.263+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:37:20.264+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:37:20.264+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:37:20.289+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:37:20.281+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name['name'], age['age'])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'age'
[2023-09-06T08:37:20.290+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:37:20.350+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.102 seconds
[2023-09-06T08:37:50.780+0000] {processor.py:157} INFO - Started process (PID=3440) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:37:50.782+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:37:50.784+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:37:50.783+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:37:50.799+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:37:50.795+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name['name'], age['age'])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'age'
[2023-09-06T08:37:50.799+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:37:50.818+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.045 seconds
[2023-09-06T08:37:55.913+0000] {processor.py:157} INFO - Started process (PID=3450) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:37:55.916+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:37:55.917+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:37:55.917+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:37:55.924+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:37:55.922+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37
    greet(namename'], age['age'])
                  ^
SyntaxError: invalid syntax
[2023-09-06T08:37:55.925+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:37:55.954+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.052 seconds
[2023-09-06T08:37:56.950+0000] {processor.py:157} INFO - Started process (PID=3455) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:37:56.952+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:37:56.955+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:37:56.954+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:37:56.966+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:37:56.963+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37
    greet(name=name'], age['age'])
                   ^
SyntaxError: invalid syntax
[2023-09-06T08:37:56.968+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:37:57.005+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.068 seconds
[2023-09-06T08:38:03.102+0000] {processor.py:157} INFO - Started process (PID=3460) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:03.104+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:38:03.106+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:38:03.106+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:03.114+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:38:03.112+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37
    greet(name=name'], ageage'])
                   ^
SyntaxError: invalid syntax
[2023-09-06T08:38:03.115+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:03.161+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.076 seconds
[2023-09-06T08:38:05.153+0000] {processor.py:157} INFO - Started process (PID=3465) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:05.156+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:38:05.159+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:38:05.158+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:05.169+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:38:05.166+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37
    greet(name=name'], age=age')
                   ^
SyntaxError: invalid syntax
[2023-09-06T08:38:05.171+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:05.230+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.091 seconds
[2023-09-06T08:38:13.337+0000] {processor.py:157} INFO - Started process (PID=3475) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:13.339+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:38:13.340+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:38:13.340+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:13.346+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:38:13.344+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37
    greet(name=name, age=age')
                              ^
SyntaxError: EOL while scanning string literal
[2023-09-06T08:38:13.347+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:13.400+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.069 seconds
[2023-09-06T08:38:17.485+0000] {processor.py:157} INFO - Started process (PID=3487) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:17.486+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:38:17.487+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:38:17.487+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:17.507+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:38:17.502+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2023-09-06T08:38:17.508+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:17.536+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.061 seconds
[2023-09-06T08:38:47.934+0000] {processor.py:157} INFO - Started process (PID=3509) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:47.938+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:38:47.940+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:38:47.939+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:47.964+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:38:47.957+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2023-09-06T08:38:47.964+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:38:47.997+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.078 seconds
[2023-09-06T08:39:06.176+0000] {processor.py:157} INFO - Started process (PID=3519) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:06.177+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:39:06.178+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:06.178+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:06.183+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:06.181+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 22
    return  'gmx'}
                 ^
SyntaxError: unmatched '}'
[2023-09-06T08:39:06.183+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:06.220+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.049 seconds
[2023-09-06T08:39:07.212+0000] {processor.py:157} INFO - Started process (PID=3524) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:07.213+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:39:07.215+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:07.215+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:07.234+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:07.230+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2023-09-06T08:39:07.234+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:07.254+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.052 seconds
[2023-09-06T08:39:09.270+0000] {processor.py:157} INFO - Started process (PID=3529) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:09.270+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:39:09.271+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:09.271+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:09.287+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:09.284+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2023-09-06T08:39:09.288+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:09.307+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.041 seconds
[2023-09-06T08:39:13.388+0000] {processor.py:157} INFO - Started process (PID=3534) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:13.391+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:39:13.395+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:13.394+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:13.403+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:13.400+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 26
    return : 20}
           ^
SyntaxError: invalid syntax
[2023-09-06T08:39:13.404+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:13.438+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.072 seconds
[2023-09-06T08:39:15.529+0000] {processor.py:157} INFO - Started process (PID=3544) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:15.532+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:39:15.536+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:15.534+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:15.550+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:15.545+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 26
    return : 20
           ^
SyntaxError: invalid syntax
[2023-09-06T08:39:15.552+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:15.615+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.100 seconds
[2023-09-06T08:39:17.664+0000] {processor.py:157} INFO - Started process (PID=3557) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:17.667+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:39:17.670+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:17.669+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:17.696+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:17.691+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2023-09-06T08:39:17.696+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:17.717+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.070 seconds
[2023-09-06T08:39:48.109+0000] {processor.py:157} INFO - Started process (PID=3579) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:48.111+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:39:48.112+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:48.112+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:48.130+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:48.125+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2023-09-06T08:39:48.131+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:48.156+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.053 seconds
[2023-09-06T08:39:51.187+0000] {processor.py:157} INFO - Started process (PID=3584) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:51.190+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:39:51.194+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:51.193+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:51.230+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:39:51.224+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2023-09-06T08:39:51.230+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:39:51.258+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.086 seconds
[2023-09-06T08:40:02.419+0000] {processor.py:157} INFO - Started process (PID=3594) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:02.427+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:40:02.430+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:40:02.429+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:02.460+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:40:02.454+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3798, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3007, in _bind
    raise TypeError('missing a required argument: {arg!r}'. \
TypeError: missing a required argument: 'last_name'
[2023-09-06T08:40:02.460+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:02.485+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.092 seconds
[2023-09-06T08:40:06.468+0000] {processor.py:157} INFO - Started process (PID=3599) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:06.468+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:40:06.469+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:40:06.469+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:06.474+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:40:06.473+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 29
    def greet(name, name, age):
    ^
SyntaxError: duplicate argument 'name' in function definition
[2023-09-06T08:40:06.474+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:06.497+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.035 seconds
[2023-09-06T08:40:10.565+0000] {processor.py:157} INFO - Started process (PID=3604) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:10.566+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:40:10.568+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:40:10.567+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:10.594+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:10.852+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:40:10.851+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:40:10.892+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:40:10.892+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:40:10.932+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.376 seconds
[2023-09-06T08:40:11.611+0000] {processor.py:157} INFO - Started process (PID=3609) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:11.613+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:40:11.615+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:40:11.614+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:11.637+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:11.659+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:40:11.658+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:40:11.811+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:40:11.811+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:40:11.872+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.268 seconds
[2023-09-06T08:40:42.231+0000] {processor.py:157} INFO - Started process (PID=3645) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:42.232+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:40:42.233+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:40:42.233+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:42.247+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:40:42.280+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:40:42.280+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:40:42.312+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:40:42.311+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:40:42.338+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.111 seconds
[2023-09-06T08:41:12.666+0000] {processor.py:157} INFO - Started process (PID=3667) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:41:12.670+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:41:12.673+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:41:12.672+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:41:12.708+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:41:12.758+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:41:12.758+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:41:12.804+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:41:12.803+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:41:12.850+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.197 seconds
[2023-09-06T08:41:43.152+0000] {processor.py:157} INFO - Started process (PID=3689) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:41:43.153+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:41:43.154+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:41:43.154+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:41:43.180+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:41:43.232+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:41:43.232+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:41:43.272+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:41:43.272+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:41:43.309+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.168 seconds
[2023-09-06T08:42:13.717+0000] {processor.py:157} INFO - Started process (PID=3711) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:42:13.718+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:42:13.720+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:42:13.719+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:42:13.740+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:42:13.771+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:42:13.771+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:42:13.799+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:42:13.799+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:42:13.831+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.123 seconds
[2023-09-06T08:42:44.094+0000] {processor.py:157} INFO - Started process (PID=3733) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:42:44.096+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:42:44.096+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:42:44.096+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:42:44.111+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:42:44.145+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:42:44.145+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:42:44.180+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:42:44.179+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:42:44.202+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.112 seconds
[2023-09-06T08:43:14.481+0000] {processor.py:157} INFO - Started process (PID=3756) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:43:14.483+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:43:14.485+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:43:14.484+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:43:14.515+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:43:14.561+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:43:14.560+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:43:14.590+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:43:14.590+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:43:14.612+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.137 seconds
[2023-09-06T08:43:44.895+0000] {processor.py:157} INFO - Started process (PID=3778) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:43:44.898+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2023-09-06T08:43:44.899+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:43:44.899+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:43:44.922+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ganza_dag_v14']) retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2023-09-06T08:43:44.965+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:43:44.965+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-06T08:43:45.011+0000] {logging_mixin.py:151} INFO - [2023-09-06T08:43:45.011+0000] {dag.py:3677} INFO - Setting next_dagrun for ganza_dag_v14 to 2023-09-06T00:00:00+00:00, run_after=2023-09-07T00:00:00+00:00
[2023-09-06T08:43:45.034+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.144 seconds
