[2023-09-06T08:33:28.241+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ganza_dag_v14.greet manual__2023-09-06T08:33:24.161005+00:00 [queued]>
[2023-09-06T08:33:28.256+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ganza_dag_v14.greet manual__2023-09-06T08:33:24.161005+00:00 [queued]>
[2023-09-06T08:33:28.257+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-06T08:33:28.280+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): greet> on 2023-09-06 08:33:24.161005+00:00
[2023-09-06T08:33:28.287+0000] {standard_task_runner.py:57} INFO - Started process 3234 to run task
[2023-09-06T08:33:28.291+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ganza_dag_v14', 'greet', 'manual__2023-09-06T08:33:24.161005+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow_api.py', '--cfg-path', '/tmp/tmp34v5es1m']
[2023-09-06T08:33:28.294+0000] {standard_task_runner.py:85} INFO - Job 143: Subtask greet
[2023-09-06T08:33:28.365+0000] {task_command.py:415} INFO - Running <TaskInstance: ganza_dag_v14.greet manual__2023-09-06T08:33:24.161005+00:00 [running]> on host 2729c554a115
[2023-09-06T08:33:28.451+0000] {abstractoperator.py:696} ERROR - Exception rendering Jinja template for task 'greet', field 'op_args'. Template: (XComArg(<Task(_PythonDecoratedOperator): get_name>, 'first_name'), XComArg(<Task(_PythonDecoratedOperator): get_name>, 'last_name'), XComArg(<Task(_PythonDecoratedOperator): get_age>, 'age'))
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 688, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 162, in render_template
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 162, in <genexpr>
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 158, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 431, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at ganza_dag_v14 with key="first_name" is not found!
[2023-09-06T08:33:28.466+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1646, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2291, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1244, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 688, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 162, in render_template
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 162, in <genexpr>
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 158, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 431, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at ganza_dag_v14 with key="first_name" is not found!
[2023-09-06T08:33:28.471+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ganza_dag_v14, task_id=greet, execution_date=20230906T083324, start_date=20230906T083328, end_date=20230906T083328
[2023-09-06T08:33:28.486+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 143 for task greet (XComArg result from get_name at ganza_dag_v14 with key="first_name" is not found!; 3234)
[2023-09-06T08:33:28.505+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-06T08:33:28.528+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
